#!/usr/bin/env python3
# coding=utf-8
"""
XML to MySQL Gateway Generator
根据 db_tables.xml 中的表定义生成对应的 MySQL Gateway 函数

Usage:
    python xml_to_mysql_gateway_generator.py

Author: Auto-generated by Claude Code
Date: 2025-07-13
"""

import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Optional, Tuple


class XMLToMySQLGatewayGenerator:
    """XML表定义到MySQL Gateway函数的生成器"""
    
    def __init__(self):
        # C++类型到参数格式化的映射
        self.cpp_param_mapping = {
            'int64_t': '{}',
            'int': '{}',
            'double': '{}',
            'float': '{}',
            'char': "'{}'",  # 字符串类型需要单引号
            'bool': '{}',
            'uint64_t': '{}',
            'uint32_t': '{}',
            'uint16_t': '{}',
            'uint8_t': '{}',
            'string': "'{}'",
        }
    
    def _get_cpp_type_for_struct_field(self, field_name: str, field_type: str, size: Optional[str] = None) -> str:
        """根据字段名和类型返回C++结构体中的实际类型"""
        # 根据字段名推断特殊类型
        if field_name == 'datetime':
            return 'DateTimeCs'
        elif field_name == 'market':
            return 'MarketCs'  
        elif field_name == 'instrument':
            return 'InstrumentCs'
        elif field_type == 'char' and size == '1':
            return 'char'
        elif field_type == 'char' and size:
            # 对于char[N]类型，在结构体中是字符数组
            return f'char[{size}]'
        else:
            return field_type
    
    def _format_sql_value(self, field_type: str, field_name: str, size: Optional[str] = None) -> str:
        """格式化SQL值的占位符"""
        if field_type == 'char' or field_name in ['datetime', 'market', 'instrument']:
            return "'{}'"
        else:
            return "{}"
    
    def _parse_struct_xml(self, struct_element: ET.Element) -> Dict:
        """解析结构体定义"""
        struct_info = {
            'name': struct_element.get('name'),
            'comment': struct_element.get('comment', ''),
            'fields': []
        }
        
        # 解析字段
        fields_element = struct_element.find('fields')
        if fields_element is not None:
            for field in fields_element.findall('field'):
                field_info = {
                    'name': field.get('name'),
                    'type': field.get('type'),
                    'size': field.get('size'),
                    'not_null': field.get('not_null', 'false').lower() == 'true',
                    'comment': field.get('comment', ''),
                    'default': field.get('default'),
                    'cpp_type': self._get_cpp_type_for_struct_field(
                        field.get('name'), 
                        field.get('type'), 
                        field.get('size')
                    )
                }
                struct_info['fields'].append(field_info)
        
        return struct_info
    
    def _parse_table_xml(self, table_element: ET.Element, structs_dict: Dict) -> Dict:
        """解析单个表的XML定义

        支持两种格式：
        1. 新格式：<table name="Done"> 直接包含<fields>，表名为结构体名
        2. 旧格式：<table name="done" struct="Done"> 引用结构体定义
        """
        table_name = table_element.get('name')
        struct_name = table_element.get('struct', table_name)  # 如果没有struct属性，使用name作为struct名

        # 将表名转换为小写（Done -> done, KLine_1M -> kline_1m）
        sql_table_name = table_name.lower()

        table_info = {
            'name': sql_table_name,  # SQL表名（小写）
            'struct': struct_name,   # C++结构体名（首字母大写）
            'comment': table_element.get('comment', ''),
            'fields': [],
            'primary_key': [],
            'indexes': [],
            'options': {}
        }

        # 新格式：直接从table元素解析fields
        fields_element = table_element.find('fields')
        if fields_element is not None:
            for field in fields_element.findall('field'):
                field_info = {
                    'name': field.get('name'),
                    'type': field.get('type'),
                    'size': field.get('size'),
                    'not_null': field.get('not_null', 'false').lower() == 'true',
                    'comment': field.get('comment', ''),
                    'default': field.get('default'),
                    'cpp_type': self._get_cpp_type_for_struct_field(
                        field.get('name'),
                        field.get('type'),
                        field.get('size')
                    )
                }
                table_info['fields'].append(field_info)
        # 旧格式：从结构体定义中获取字段信息
        elif struct_name in structs_dict:
            table_info['fields'] = structs_dict[struct_name]['fields'].copy()

        # 解析主键
        primary_key_element = table_element.find('primary_key')
        if primary_key_element is not None:
            for field in primary_key_element.findall('field'):
                table_info['primary_key'].append(field.text)

        return table_info
    
    def _generate_insert_function(self, table_info: Dict) -> str:
        """生成INSERT函数"""
        table_name = table_info['name']
        struct_name = table_info['struct']
        
        # 生成函数声明
        func_name = f"OnSet{struct_name}_{table_name.replace('_', '').upper()}"
        lines = []
        
        # 函数注释
        lines.append(f"// 插入{table_info['comment']}数据")
        lines.append(f"void MySqlGateway::{func_name}(int msg_id, const BufPtr buffer) {{")
        lines.append(f"    const auto& recv_data = *reinterpret_cast<const {struct_name}*>(buffer->Data());")
        lines.append(f"    SPDLOG_INFO(\"{{}}\", zrt::to_str(recv_data));")
        lines.append("")
        
        # 生成字段列表
        field_names = [field['name'] for field in table_info['fields']]
        field_list = ', '.join([f"`{name}`" for name in field_names])
        
        # 生成VALUES部分的占位符
        value_placeholders = []
        value_params = []
        update_clauses = []
        
        for field in table_info['fields']:
            placeholder = self._format_sql_value(field['type'], field['name'], field['size'])
            value_placeholders.append(placeholder)
            
            # 根据字段类型生成参数
            if field['cpp_type'] in ['DateTimeCs', 'MarketCs', 'InstrumentCs']:
                value_params.append(f"recv_data.{field['name']}")
            elif field['cpp_type'].startswith('char['):
                value_params.append(f"recv_data.{field['name']}")
            else:
                value_params.append(f"recv_data.{field['name']}")
            
            # 对于非主键字段，添加到UPDATE子句中
            if field['name'] not in table_info['primary_key']:
                update_clauses.append(f"{field['name']}={placeholder}")
        
        # 生成SQL语句
        lines.append("    // 构建INSERT ON DUPLICATE KEY UPDATE语句")
        lines.append("    std::string sql = fmt::format(")
        lines.append(f"        \"INSERT INTO {table_name} ({field_list}) \"")
        lines.append(f"        \"VALUES ({', '.join(value_placeholders)}) \"")
        lines.append("        \"ON DUPLICATE KEY UPDATE \"")
        
        # 添加UPDATE子句
        if update_clauses:
            for i, clause in enumerate(update_clauses):
                if i == len(update_clauses) - 1:
                    lines.append(f"        \"{clause}, update_time=CURRENT_TIMESTAMP\",")
                else:
                    lines.append(f"        \"{clause}, \"")
        
        # 添加参数列表
        lines.append(f"        {', '.join(value_params)}")
        
        # 如果有UPDATE子句，添加重复的参数
        if update_clauses:
            update_params = [param for i, param in enumerate(value_params) 
                           if table_info['fields'][i]['name'] not in table_info['primary_key']]
            if update_params:
                lines.append(f"        , {', '.join(update_params)}")
        
        lines.append("    );")
        lines.append("")
        lines.append("    m_mysql_client->Execute(sql);")
        lines.append("}")
        
        return '\n'.join(lines)
    
    def _generate_delete_function(self, table_info: Dict) -> str:
        """生成DELETE函数"""
        table_name = table_info['name']
        struct_name = table_info['struct']
        
        # 生成函数声明
        func_name = f"OnDel{struct_name}_{table_name.replace('_', '').upper()}"
        lines = []
        
        # 函数注释
        lines.append(f"// 删除{table_info['comment']}数据")
        lines.append(f"void MySqlGateway::{func_name}(int msg_id, const BufPtr buffer) {{")
        lines.append(f"    const auto& recv_data = *reinterpret_cast<const {struct_name}*>(buffer->Data());")
        lines.append(f"    SPDLOG_INFO(\"{{}}\", zrt::to_str(recv_data));")
        lines.append("")
        
        # 生成WHERE条件 - 使用主键字段
        where_conditions = []
        where_params = []
        
        for pk_field in table_info['primary_key']:
            # 找到对应的字段信息
            field_info = next((f for f in table_info['fields'] if f['name'] == pk_field), None)
            if field_info:
                placeholder = self._format_sql_value(field_info['type'], field_info['name'], field_info['size'])
                where_conditions.append(f"{pk_field}={placeholder}")
                
                if field_info['cpp_type'] in ['DateTimeCs', 'MarketCs', 'InstrumentCs']:
                    where_params.append(f"recv_data.{pk_field}")
                else:
                    where_params.append(f"recv_data.{pk_field}")
        
        # 生成SQL语句
        where_clause = ' AND '.join(where_conditions)
        lines.append(f"    // 删除指定{table_info['comment']}")
        lines.append("    std::string sql = fmt::format(")
        lines.append(f"        \"DELETE FROM {table_name} WHERE {where_clause}\",")
        lines.append(f"        {', '.join(where_params)}")
        lines.append("    );")
        lines.append("")
        lines.append("    m_mysql_client->Execute(sql);")
        lines.append("}")
        
        return '\n'.join(lines)
    
    def _generate_message_ids(self, table_info: Dict) -> List[str]:
        """生成消息ID定义"""
        table_name = table_info['name']
        struct_name = table_info['struct']
        
        insert_msg = f"kSet{struct_name}_{table_name.replace('_', '').upper()}"
        delete_msg = f"kDel{struct_name}_{table_name.replace('_', '').upper()}"
        
        return [insert_msg, delete_msg]
    
    def _generate_handler_registrations(self, table_info: Dict) -> List[str]:
        """生成处理器注册代码"""
        table_name = table_info['name']
        struct_name = table_info['struct']
        
        insert_func = f"OnSet{struct_name}_{table_name.replace('_', '').upper()}"
        delete_func = f"OnDel{struct_name}_{table_name.replace('_', '').upper()}"
        
        insert_msg = f"kSet{struct_name}_{table_name.replace('_', '').upper()}"
        delete_msg = f"kDel{struct_name}_{table_name.replace('_', '').upper()}"
        
        return [
            f"ZRT_ADD_HANDLER({insert_msg}, MySqlGateway::{insert_func});",
            f"ZRT_ADD_HANDLER({delete_msg}, MySqlGateway::{delete_func});"
        ]
    
    def _generate_header_declarations(self, table_info: Dict) -> List[str]:
        """生成头文件声明"""
        table_name = table_info['name']
        struct_name = table_info['struct']
        
        insert_func = f"OnSet{struct_name}_{table_name.replace('_', '').upper()}"
        delete_func = f"OnDel{struct_name}_{table_name.replace('_', '').upper()}"
        
        return [
            f"void {insert_func}(int msg_id, const BufPtr buffer);",
            f"void {delete_func}(int msg_id, const BufPtr buffer);"
        ]
    
    def parse_xml_file(self, xml_path: str) -> List[Dict]:
        """解析XML文件，返回所有表的定义

        兼容两种格式:
        1. 旧格式: 单个db_tables.xml文件包含所有结构体和表定义
        2. 新格式: db_tables目录下的多个XML文件，每个文件一个struct或table
        """
        if os.path.isfile(xml_path):
            # 旧格式: 单个文件
            return self._parse_single_xml_file(xml_path)
        elif os.path.isdir(xml_path):
            # 新格式: 目录
            return self._parse_xml_directory(xml_path)
        else:
            raise FileNotFoundError(f"XML文件或目录不存在: {xml_path}")

    def _parse_single_xml_file(self, xml_path: str) -> List[Dict]:
        """解析单个XML文件（旧格式）"""
        try:
            tree = ET.parse(xml_path)
            root = tree.getroot()
        except ET.ParseError as e:
            raise ValueError(f"XML文件解析错误: {e}")

        # 解析结构体定义
        structs_dict = {}
        structs_element = root.find('structs')
        if structs_element is not None:
            for struct_element in structs_element.findall('struct'):
                struct_info = self._parse_struct_xml(struct_element)
                structs_dict[struct_info['name']] = struct_info

        # 解析表定义
        tables = []
        tables_element = root.find('tables')
        if tables_element is not None:
            for table_element in tables_element.findall('table'):
                table_info = self._parse_table_xml(table_element, structs_dict)
                tables.append(table_info)

        return tables

    def _parse_xml_directory(self, xml_dir: str) -> List[Dict]:
        """解析db_tables目录下的所有XML文件（新格式）

        新格式：每个XML文件是一个<table>元素，包含所有定义
        旧格式兼容：<struct>元素单独定义，<table>元素引用struct
        """
        structs_dict = {}
        tables = []

        # 获取所有XML文件
        xml_files = sorted([f for f in os.listdir(xml_dir) if f.endswith('.xml') and not f.startswith('db_tables_old')])

        # 第一遍: 解析所有结构体（兼容旧格式）
        for xml_file in xml_files:
            xml_path = os.path.join(xml_dir, xml_file)
            try:
                tree = ET.parse(xml_path)
                root = tree.getroot()

                if root.tag == 'struct':
                    struct_info = self._parse_struct_xml(root)
                    structs_dict[struct_info['name']] = struct_info
                    print(f"  加载结构体: {struct_info['name']} <- {xml_file}")
            except ET.ParseError as e:
                print(f"  警告: 解析文件 {xml_file} 失败: {e}")

        # 第二遍: 解析所有表定义（新格式）
        for xml_file in xml_files:
            xml_path = os.path.join(xml_dir, xml_file)
            try:
                tree = ET.parse(xml_path)
                root = tree.getroot()

                if root.tag == 'table':
                    table_info = self._parse_table_xml(root, structs_dict)
                    tables.append(table_info)
                    print(f"  加载表: {table_info['name']} (struct: {table_info['struct']}) <- {xml_file}")
            except ET.ParseError as e:
                print(f"  警告: 解析文件 {xml_file} 失败: {e}")

        return tables
    
    def generate_gateway_functions(self, xml_path: str, mysql_gateway_cpp_path: str, mysql_gateway_h_path: str, type_define_h_path: str) -> Dict[str, str]:
        """生成MySQL Gateway函数代码并添加到现有文件中"""
        tables = self.parse_xml_file(xml_path)
        
        results = {
            'functions': [],
            'message_ids': [],
            'handler_registrations': [],
            'header_declarations': []
        }
        
        print(f"找到 {len(tables)} 个表定义")
        
        for table_info in tables:
            try:
                # 生成函数代码
                insert_func = self._generate_insert_function(table_info)
                delete_func = self._generate_delete_function(table_info)
                
                results['functions'].append(insert_func)
                results['functions'].append(delete_func)
                
                # 生成消息ID
                msg_ids = self._generate_message_ids(table_info)
                results['message_ids'].extend(msg_ids)
                
                # 生成处理器注册
                handlers = self._generate_handler_registrations(table_info)
                results['handler_registrations'].extend(handlers)
                
                # 生成头文件声明
                declarations = self._generate_header_declarations(table_info)
                results['header_declarations'].extend(declarations)
                
                print(f"✓ 生成表 {table_info['name']} 的Gateway函数")
                
            except Exception as e:
                print(f"✗ 生成表 {table_info['name']} 失败: {e}")
        
        # 更新现有文件
        self._update_existing_files(results, mysql_gateway_cpp_path, mysql_gateway_h_path, type_define_h_path)
        
        return results
    
    def _update_existing_files(self, results: Dict, mysql_gateway_cpp_path: str, mysql_gateway_h_path: str, type_define_h_path: str):
        """更新现有的代码文件"""
        
        # 1. 更新 mysql_gateway.cpp 文件
        self._update_mysql_gateway_cpp(results, mysql_gateway_cpp_path)
        
        # 2. 更新 mysql_gateway.h 文件
        self._update_mysql_gateway_h(results, mysql_gateway_h_path)
        
        # 3. 更新 type_define.h 文件
        self._update_type_define_h(results, type_define_h_path)
    
    def _update_mysql_gateway_cpp(self, results: Dict, file_path: str):
        """更新 mysql_gateway.cpp 文件"""
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        content_modified = False
        
        # 1. 在Init()函数中添加处理器注册（幂等性检查）
        for handler_reg in results['handler_registrations']:
            if handler_reg not in content:
                old_handler = 'ZRT_ADD_HANDLER(kDelAllStrategyInfo, MySqlGateway::OnDelAllStrategyInfo);'
                if old_handler in content:
                    content = content.replace(old_handler, old_handler + '\n    ' + handler_reg)
                    content_modified = True
        
        # 2. 在文件末尾添加函数实现（幂等性检查）
        for func_code in results['functions']:
            # 提取函数名用于检查
            func_name_match = func_code.split('::')[1].split('(')[0] if '::' in func_code else None
            if func_name_match and func_name_match not in content:
                if not content.endswith('\n\n'):
                    content += '\n\n'
                content += f"// 自动生成的函数实现\n"
                content += func_code + '\n\n'
                content_modified = True
        
        if content_modified:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✓ 更新文件: {file_path}")
        else:
            print(f"○ 文件无需更新: {file_path}")
    
    def _update_mysql_gateway_h(self, results: Dict, file_path: str):
        """更新 mysql_gateway.h 文件"""
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        content_modified = False
        
        # 在OnDelAllStrategyInfo函数声明后添加新的函数声明（幂等性检查）
        for declaration in results['header_declarations']:
            if declaration not in content:
                old_decl = 'void OnDelAllStrategyInfo(int msg_id, const BufPtr buffer);'
                if old_decl in content:
                    content = content.replace(old_decl, old_decl + '\n    ' + declaration)
                    content_modified = True
        
        if content_modified:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✓ 更新文件: {file_path}")
        else:
            print(f"○ 文件无需更新: {file_path}")
    
    def _update_type_define_h(self, results: Dict, file_path: str):
        """更新 type_define.h 文件"""
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        content_modified = False
        
        # 在kDelAllStrategyInfo后添加新的消息ID（幂等性检查）
        for msg_id in results['message_ids']:
            if msg_id not in content:
                old_msg = 'kDelAllStrategyInfo,'
                if old_msg in content:
                    content = content.replace(old_msg, old_msg + '\n    ' + msg_id + ',')
                    content_modified = True
        
        if content_modified:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✓ 更新文件: {file_path}")
        else:
            print(f"○ 文件无需更新: {file_path}")
    
if __name__ == '__main__':
    # 配置参数
    # 使用db_tables目录（新格式）
    xml_path = '../db_tables'
    mysql_gateway_cpp_path = '../../../strategy_engine/mysql_gateway.cpp'
    mysql_gateway_h_path = '../../../strategy_engine/mysql_gateway.h'
    type_define_h_path = '../../../interface/type_define.h'

    # 转换为绝对路径
    xml_path = os.path.abspath(xml_path)
    mysql_gateway_cpp_path = os.path.abspath(mysql_gateway_cpp_path)
    mysql_gateway_h_path = os.path.abspath(mysql_gateway_h_path)
    type_define_h_path = os.path.abspath(type_define_h_path)

    print(f"XML文件路径: {xml_path}")
    print(f"mysql_gateway.cpp路径: {mysql_gateway_cpp_path}")
    print(f"mysql_gateway.h路径: {mysql_gateway_h_path}")
    print(f"type_define.h路径: {type_define_h_path}")

    generator = XMLToMySQLGatewayGenerator()
    results = generator.generate_gateway_functions(xml_path, mysql_gateway_cpp_path, mysql_gateway_h_path, type_define_h_path)

    print(f"\n成功生成并添加MySQL Gateway代码:")
    print(f"  - 函数数量: {len(results['functions'])}")
    print(f"  - 消息ID数量: {len(results['message_ids'])}")
    print(f"  - 处理器注册数量: {len(results['handler_registrations'])}")
    print(f"  - 头文件声明数量: {len(results['header_declarations'])}")

    print(f"\n已更新现有文件!")