// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: desktop_gateway.proto

#include "desktop_gateway.pb.h"
#include "desktop_gateway.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace gtrade {
namespace desktop_gateway {

static const char* DesktopGateway_method_names[] = {
  "/gtrade.desktop_gateway.DesktopGateway/Login",
  "/gtrade.desktop_gateway.DesktopGateway/GetStrategies",
  "/gtrade.desktop_gateway.DesktopGateway/GetStrategy",
  "/gtrade.desktop_gateway.DesktopGateway/AddStrategy",
  "/gtrade.desktop_gateway.DesktopGateway/DeleteStrategy",
  "/gtrade.desktop_gateway.DesktopGateway/StartStrategy",
  "/gtrade.desktop_gateway.DesktopGateway/StopStrategy",
  "/gtrade.desktop_gateway.DesktopGateway/RestartStrategy",
  "/gtrade.desktop_gateway.DesktopGateway/BatchOperation",
  "/gtrade.desktop_gateway.DesktopGateway/GetOrders",
  "/gtrade.desktop_gateway.DesktopGateway/GetTrades",
  "/gtrade.desktop_gateway.DesktopGateway/GetPositions",
  "/gtrade.desktop_gateway.DesktopGateway/GetTemplates",
  "/gtrade.desktop_gateway.DesktopGateway/GetTemplateConfig",
  "/gtrade.desktop_gateway.DesktopGateway/GetDictionary",
};

std::unique_ptr< DesktopGateway::Stub> DesktopGateway::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DesktopGateway::Stub> stub(new DesktopGateway::Stub(channel, options));
  return stub;
}

DesktopGateway::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(DesktopGateway_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStrategies_(DesktopGateway_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStrategy_(DesktopGateway_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddStrategy_(DesktopGateway_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteStrategy_(DesktopGateway_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartStrategy_(DesktopGateway_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopStrategy_(DesktopGateway_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RestartStrategy_(DesktopGateway_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchOperation_(DesktopGateway_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetOrders_(DesktopGateway_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTrades_(DesktopGateway_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPositions_(DesktopGateway_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTemplates_(DesktopGateway_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTemplateConfig_(DesktopGateway_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDictionary_(DesktopGateway_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DesktopGateway::Stub::Login(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::LoginRequest& request, ::gtrade::desktop_gateway::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::LoginRequest, ::gtrade::desktop_gateway::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void DesktopGateway::Stub::async::Login(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::LoginRequest* request, ::gtrade::desktop_gateway::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::LoginRequest, ::gtrade::desktop_gateway::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::Login(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::LoginRequest* request, ::gtrade::desktop_gateway::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::LoginResponse>* DesktopGateway::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::LoginResponse, ::gtrade::desktop_gateway::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::LoginResponse>* DesktopGateway::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetStrategies(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategiesRequest& request, ::gtrade::desktop_gateway::GetStrategiesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetStrategiesRequest, ::gtrade::desktop_gateway::GetStrategiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStrategies_, context, request, response);
}

void DesktopGateway::Stub::async::GetStrategies(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategiesRequest* request, ::gtrade::desktop_gateway::GetStrategiesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetStrategiesRequest, ::gtrade::desktop_gateway::GetStrategiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategies_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetStrategies(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategiesRequest* request, ::gtrade::desktop_gateway::GetStrategiesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategies_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetStrategiesResponse>* DesktopGateway::Stub::PrepareAsyncGetStrategiesRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategiesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetStrategiesResponse, ::gtrade::desktop_gateway::GetStrategiesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStrategies_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetStrategiesResponse>* DesktopGateway::Stub::AsyncGetStrategiesRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategiesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStrategiesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategyRequest& request, ::gtrade::desktop_gateway::GetStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetStrategyRequest, ::gtrade::desktop_gateway::GetStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStrategy_, context, request, response);
}

void DesktopGateway::Stub::async::GetStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategyRequest* request, ::gtrade::desktop_gateway::GetStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetStrategyRequest, ::gtrade::desktop_gateway::GetStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategy_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategyRequest* request, ::gtrade::desktop_gateway::GetStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetStrategyResponse>* DesktopGateway::Stub::PrepareAsyncGetStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetStrategyResponse, ::gtrade::desktop_gateway::GetStrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetStrategyResponse>* DesktopGateway::Stub::AsyncGetStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::AddStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::AddStrategyRequest& request, ::gtrade::desktop_gateway::AddStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::AddStrategyRequest, ::gtrade::desktop_gateway::AddStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddStrategy_, context, request, response);
}

void DesktopGateway::Stub::async::AddStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::AddStrategyRequest* request, ::gtrade::desktop_gateway::AddStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::AddStrategyRequest, ::gtrade::desktop_gateway::AddStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddStrategy_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::AddStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::AddStrategyRequest* request, ::gtrade::desktop_gateway::AddStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::AddStrategyResponse>* DesktopGateway::Stub::PrepareAsyncAddStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::AddStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::AddStrategyResponse, ::gtrade::desktop_gateway::AddStrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::AddStrategyResponse>* DesktopGateway::Stub::AsyncAddStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::AddStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::DeleteStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::DeleteStrategyRequest& request, ::gtrade::desktop_gateway::DeleteStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::DeleteStrategyRequest, ::gtrade::desktop_gateway::DeleteStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteStrategy_, context, request, response);
}

void DesktopGateway::Stub::async::DeleteStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::DeleteStrategyRequest* request, ::gtrade::desktop_gateway::DeleteStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::DeleteStrategyRequest, ::gtrade::desktop_gateway::DeleteStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStrategy_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::DeleteStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::DeleteStrategyRequest* request, ::gtrade::desktop_gateway::DeleteStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::DeleteStrategyResponse>* DesktopGateway::Stub::PrepareAsyncDeleteStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::DeleteStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::DeleteStrategyResponse, ::gtrade::desktop_gateway::DeleteStrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::DeleteStrategyResponse>* DesktopGateway::Stub::AsyncDeleteStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::DeleteStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::StartStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StartStrategyRequest& request, ::gtrade::desktop_gateway::StartStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::StartStrategyRequest, ::gtrade::desktop_gateway::StartStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartStrategy_, context, request, response);
}

void DesktopGateway::Stub::async::StartStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StartStrategyRequest* request, ::gtrade::desktop_gateway::StartStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::StartStrategyRequest, ::gtrade::desktop_gateway::StartStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStrategy_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::StartStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StartStrategyRequest* request, ::gtrade::desktop_gateway::StartStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::StartStrategyResponse>* DesktopGateway::Stub::PrepareAsyncStartStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StartStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::StartStrategyResponse, ::gtrade::desktop_gateway::StartStrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::StartStrategyResponse>* DesktopGateway::Stub::AsyncStartStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StartStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::StopStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StopStrategyRequest& request, ::gtrade::desktop_gateway::StopStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::StopStrategyRequest, ::gtrade::desktop_gateway::StopStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopStrategy_, context, request, response);
}

void DesktopGateway::Stub::async::StopStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StopStrategyRequest* request, ::gtrade::desktop_gateway::StopStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::StopStrategyRequest, ::gtrade::desktop_gateway::StopStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStrategy_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::StopStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StopStrategyRequest* request, ::gtrade::desktop_gateway::StopStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::StopStrategyResponse>* DesktopGateway::Stub::PrepareAsyncStopStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StopStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::StopStrategyResponse, ::gtrade::desktop_gateway::StopStrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::StopStrategyResponse>* DesktopGateway::Stub::AsyncStopStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::StopStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::RestartStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::RestartStrategyRequest& request, ::gtrade::desktop_gateway::RestartStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::RestartStrategyRequest, ::gtrade::desktop_gateway::RestartStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RestartStrategy_, context, request, response);
}

void DesktopGateway::Stub::async::RestartStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::RestartStrategyRequest* request, ::gtrade::desktop_gateway::RestartStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::RestartStrategyRequest, ::gtrade::desktop_gateway::RestartStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestartStrategy_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::RestartStrategy(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::RestartStrategyRequest* request, ::gtrade::desktop_gateway::RestartStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestartStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::RestartStrategyResponse>* DesktopGateway::Stub::PrepareAsyncRestartStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::RestartStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::RestartStrategyResponse, ::gtrade::desktop_gateway::RestartStrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RestartStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::RestartStrategyResponse>* DesktopGateway::Stub::AsyncRestartStrategyRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::RestartStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRestartStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::BatchOperation(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::BatchOperationRequest& request, ::gtrade::desktop_gateway::BatchOperationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::BatchOperationRequest, ::gtrade::desktop_gateway::BatchOperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchOperation_, context, request, response);
}

void DesktopGateway::Stub::async::BatchOperation(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::BatchOperationRequest* request, ::gtrade::desktop_gateway::BatchOperationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::BatchOperationRequest, ::gtrade::desktop_gateway::BatchOperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchOperation_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::BatchOperation(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::BatchOperationRequest* request, ::gtrade::desktop_gateway::BatchOperationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchOperation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::BatchOperationResponse>* DesktopGateway::Stub::PrepareAsyncBatchOperationRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::BatchOperationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::BatchOperationResponse, ::gtrade::desktop_gateway::BatchOperationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchOperation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::BatchOperationResponse>* DesktopGateway::Stub::AsyncBatchOperationRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::BatchOperationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchOperationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetOrders(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetOrdersRequest& request, ::gtrade::desktop_gateway::GetOrdersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetOrdersRequest, ::gtrade::desktop_gateway::GetOrdersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetOrders_, context, request, response);
}

void DesktopGateway::Stub::async::GetOrders(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetOrdersRequest* request, ::gtrade::desktop_gateway::GetOrdersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetOrdersRequest, ::gtrade::desktop_gateway::GetOrdersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrders_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetOrders(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetOrdersRequest* request, ::gtrade::desktop_gateway::GetOrdersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrders_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetOrdersResponse>* DesktopGateway::Stub::PrepareAsyncGetOrdersRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetOrdersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetOrdersResponse, ::gtrade::desktop_gateway::GetOrdersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetOrders_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetOrdersResponse>* DesktopGateway::Stub::AsyncGetOrdersRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetOrdersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetOrdersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetTrades(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTradesRequest& request, ::gtrade::desktop_gateway::GetTradesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetTradesRequest, ::gtrade::desktop_gateway::GetTradesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTrades_, context, request, response);
}

void DesktopGateway::Stub::async::GetTrades(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTradesRequest* request, ::gtrade::desktop_gateway::GetTradesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetTradesRequest, ::gtrade::desktop_gateway::GetTradesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTrades_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetTrades(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTradesRequest* request, ::gtrade::desktop_gateway::GetTradesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTrades_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetTradesResponse>* DesktopGateway::Stub::PrepareAsyncGetTradesRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTradesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetTradesResponse, ::gtrade::desktop_gateway::GetTradesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTrades_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetTradesResponse>* DesktopGateway::Stub::AsyncGetTradesRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTradesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTradesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetPositions(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetPositionsRequest& request, ::gtrade::desktop_gateway::GetPositionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetPositionsRequest, ::gtrade::desktop_gateway::GetPositionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPositions_, context, request, response);
}

void DesktopGateway::Stub::async::GetPositions(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetPositionsRequest* request, ::gtrade::desktop_gateway::GetPositionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetPositionsRequest, ::gtrade::desktop_gateway::GetPositionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPositions_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetPositions(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetPositionsRequest* request, ::gtrade::desktop_gateway::GetPositionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPositions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetPositionsResponse>* DesktopGateway::Stub::PrepareAsyncGetPositionsRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetPositionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetPositionsResponse, ::gtrade::desktop_gateway::GetPositionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPositions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetPositionsResponse>* DesktopGateway::Stub::AsyncGetPositionsRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetPositionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPositionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetTemplates(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplatesRequest& request, ::gtrade::desktop_gateway::GetTemplatesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetTemplatesRequest, ::gtrade::desktop_gateway::GetTemplatesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTemplates_, context, request, response);
}

void DesktopGateway::Stub::async::GetTemplates(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplatesRequest* request, ::gtrade::desktop_gateway::GetTemplatesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetTemplatesRequest, ::gtrade::desktop_gateway::GetTemplatesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTemplates_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetTemplates(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplatesRequest* request, ::gtrade::desktop_gateway::GetTemplatesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTemplates_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetTemplatesResponse>* DesktopGateway::Stub::PrepareAsyncGetTemplatesRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplatesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetTemplatesResponse, ::gtrade::desktop_gateway::GetTemplatesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTemplates_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetTemplatesResponse>* DesktopGateway::Stub::AsyncGetTemplatesRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplatesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTemplatesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetTemplateConfig(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplateConfigRequest& request, ::gtrade::desktop_gateway::GetTemplateConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetTemplateConfigRequest, ::gtrade::desktop_gateway::GetTemplateConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTemplateConfig_, context, request, response);
}

void DesktopGateway::Stub::async::GetTemplateConfig(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplateConfigRequest* request, ::gtrade::desktop_gateway::GetTemplateConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetTemplateConfigRequest, ::gtrade::desktop_gateway::GetTemplateConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTemplateConfig_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetTemplateConfig(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplateConfigRequest* request, ::gtrade::desktop_gateway::GetTemplateConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTemplateConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetTemplateConfigResponse>* DesktopGateway::Stub::PrepareAsyncGetTemplateConfigRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplateConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetTemplateConfigResponse, ::gtrade::desktop_gateway::GetTemplateConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTemplateConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetTemplateConfigResponse>* DesktopGateway::Stub::AsyncGetTemplateConfigRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetTemplateConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTemplateConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DesktopGateway::Stub::GetDictionary(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetDictionaryRequest& request, ::gtrade::desktop_gateway::GetDictionaryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gtrade::desktop_gateway::GetDictionaryRequest, ::gtrade::desktop_gateway::GetDictionaryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDictionary_, context, request, response);
}

void DesktopGateway::Stub::async::GetDictionary(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetDictionaryRequest* request, ::gtrade::desktop_gateway::GetDictionaryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gtrade::desktop_gateway::GetDictionaryRequest, ::gtrade::desktop_gateway::GetDictionaryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDictionary_, context, request, response, std::move(f));
}

void DesktopGateway::Stub::async::GetDictionary(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetDictionaryRequest* request, ::gtrade::desktop_gateway::GetDictionaryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDictionary_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetDictionaryResponse>* DesktopGateway::Stub::PrepareAsyncGetDictionaryRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetDictionaryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gtrade::desktop_gateway::GetDictionaryResponse, ::gtrade::desktop_gateway::GetDictionaryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDictionary_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gtrade::desktop_gateway::GetDictionaryResponse>* DesktopGateway::Stub::AsyncGetDictionaryRaw(::grpc::ClientContext* context, const ::gtrade::desktop_gateway::GetDictionaryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDictionaryRaw(context, request, cq);
  result->StartCall();
  return result;
}

DesktopGateway::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::LoginRequest, ::gtrade::desktop_gateway::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::LoginRequest* req,
             ::gtrade::desktop_gateway::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetStrategiesRequest, ::gtrade::desktop_gateway::GetStrategiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetStrategiesRequest* req,
             ::gtrade::desktop_gateway::GetStrategiesResponse* resp) {
               return service->GetStrategies(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetStrategyRequest, ::gtrade::desktop_gateway::GetStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetStrategyRequest* req,
             ::gtrade::desktop_gateway::GetStrategyResponse* resp) {
               return service->GetStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::AddStrategyRequest, ::gtrade::desktop_gateway::AddStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::AddStrategyRequest* req,
             ::gtrade::desktop_gateway::AddStrategyResponse* resp) {
               return service->AddStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::DeleteStrategyRequest, ::gtrade::desktop_gateway::DeleteStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::DeleteStrategyRequest* req,
             ::gtrade::desktop_gateway::DeleteStrategyResponse* resp) {
               return service->DeleteStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::StartStrategyRequest, ::gtrade::desktop_gateway::StartStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::StartStrategyRequest* req,
             ::gtrade::desktop_gateway::StartStrategyResponse* resp) {
               return service->StartStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::StopStrategyRequest, ::gtrade::desktop_gateway::StopStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::StopStrategyRequest* req,
             ::gtrade::desktop_gateway::StopStrategyResponse* resp) {
               return service->StopStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::RestartStrategyRequest, ::gtrade::desktop_gateway::RestartStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::RestartStrategyRequest* req,
             ::gtrade::desktop_gateway::RestartStrategyResponse* resp) {
               return service->RestartStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::BatchOperationRequest, ::gtrade::desktop_gateway::BatchOperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::BatchOperationRequest* req,
             ::gtrade::desktop_gateway::BatchOperationResponse* resp) {
               return service->BatchOperation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetOrdersRequest, ::gtrade::desktop_gateway::GetOrdersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetOrdersRequest* req,
             ::gtrade::desktop_gateway::GetOrdersResponse* resp) {
               return service->GetOrders(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetTradesRequest, ::gtrade::desktop_gateway::GetTradesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetTradesRequest* req,
             ::gtrade::desktop_gateway::GetTradesResponse* resp) {
               return service->GetTrades(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetPositionsRequest, ::gtrade::desktop_gateway::GetPositionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetPositionsRequest* req,
             ::gtrade::desktop_gateway::GetPositionsResponse* resp) {
               return service->GetPositions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetTemplatesRequest, ::gtrade::desktop_gateway::GetTemplatesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetTemplatesRequest* req,
             ::gtrade::desktop_gateway::GetTemplatesResponse* resp) {
               return service->GetTemplates(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetTemplateConfigRequest, ::gtrade::desktop_gateway::GetTemplateConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetTemplateConfigRequest* req,
             ::gtrade::desktop_gateway::GetTemplateConfigResponse* resp) {
               return service->GetTemplateConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopGateway_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopGateway::Service, ::gtrade::desktop_gateway::GetDictionaryRequest, ::gtrade::desktop_gateway::GetDictionaryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopGateway::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gtrade::desktop_gateway::GetDictionaryRequest* req,
             ::gtrade::desktop_gateway::GetDictionaryResponse* resp) {
               return service->GetDictionary(ctx, req, resp);
             }, this)));
}

DesktopGateway::Service::~Service() {
}

::grpc::Status DesktopGateway::Service::Login(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::LoginRequest* request, ::gtrade::desktop_gateway::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetStrategies(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetStrategiesRequest* request, ::gtrade::desktop_gateway::GetStrategiesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetStrategy(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetStrategyRequest* request, ::gtrade::desktop_gateway::GetStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::AddStrategy(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::AddStrategyRequest* request, ::gtrade::desktop_gateway::AddStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::DeleteStrategy(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::DeleteStrategyRequest* request, ::gtrade::desktop_gateway::DeleteStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::StartStrategy(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::StartStrategyRequest* request, ::gtrade::desktop_gateway::StartStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::StopStrategy(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::StopStrategyRequest* request, ::gtrade::desktop_gateway::StopStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::RestartStrategy(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::RestartStrategyRequest* request, ::gtrade::desktop_gateway::RestartStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::BatchOperation(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::BatchOperationRequest* request, ::gtrade::desktop_gateway::BatchOperationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetOrders(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetOrdersRequest* request, ::gtrade::desktop_gateway::GetOrdersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetTrades(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetTradesRequest* request, ::gtrade::desktop_gateway::GetTradesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetPositions(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetPositionsRequest* request, ::gtrade::desktop_gateway::GetPositionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetTemplates(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetTemplatesRequest* request, ::gtrade::desktop_gateway::GetTemplatesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetTemplateConfig(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetTemplateConfigRequest* request, ::gtrade::desktop_gateway::GetTemplateConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DesktopGateway::Service::GetDictionary(::grpc::ServerContext* context, const ::gtrade::desktop_gateway::GetDictionaryRequest* request, ::gtrade::desktop_gateway::GetDictionaryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gtrade
}  // namespace desktop_gateway

