strategy_config:
#  - strategy_config/strat_sma_BTC_USDT.yml
#  - strategy_config/strat_demo_BTC_USDT.yml
#  - strategy_config/strat_fut_arbi_v3_BTC_USDT.yml
  - strategy_config/strat_backtest_validator_BTC_USDT.yml

account_config: /etc/secret.yml
db_config: /etc/secret.db.yml

logger:
  log_file: "log/gtrade_bt.log"
  async: false
  show_level: "info"
  log_level: "trace,info,error"

proxy:
  http: ""  # 从环境变量 HTTP_PROXY_HOST / HTTP_PROXY_PORT 读取
  socks5: ""

# 查询服务线程数（回测串行，不需要太多）
query_processor_num: 4

###### 回测参数 ######
# 回测起始日期UTC(YYYYmmdd_HHMM)
start_date: 20260419_0000
# 回测结束日期UTC(YYYYmmdd_HHMM)
end_date:   20260420_0000
# 回测速度倍率（非 0 backtest_interval 时此项无效）
backtest_rate: 1
# 回测间隔(毫秒, 非0会覆盖回测速度倍率)
backtest_interval: 1
# csv行情数据目录
csv_quote_base_dir: /root/data_repo
# 成交委托输出目录
backtest_out_dir: /root/backtest
# 成交模式: i - immediate(即时成交), s - simulate(模拟撮合)
fill_mode: i
