#!/usr/bin/env python3
# coding=utf-8
"""
Dict YAML to C++ Header Generator
根据 dict.yml 中的枚举定义生成对应的 C++ 结构体代码

Usage:
    python dict_generator.py

Author: Auto-generated by Claude Code
Date: 2025-11-20
"""

import os
import sys
import yaml
from pathlib import Path
from typing import Dict, List, Any

# 导入lazy_write_file工具函数
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from utils.file_utils import lazy_write_file


class DictGenerator:
    """字典YAML到C++头文件的生成器"""

    def __init__(self):
        # 获取项目根目录
        script_dir = Path(__file__).parent
        self.project_root = script_dir.parent.parent.parent
        self.yaml_path = self.project_root / 'src' / 'common' / 'dict.yml'
        self.header_path = self.project_root / 'src' / 'common' / 'dict.h'

    def load_yaml(self) -> Dict[str, Any]:
        """加载YAML文件"""
        if not self.yaml_path.exists():
            raise FileNotFoundError(f"YAML文件不存在: {self.yaml_path}")

        with open(self.yaml_path, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)

        return data or {}

    def generate_struct_code(self, struct_name: str, struct_def: Dict[str, Any]) -> str:
        """生成单个结构体的C++代码

        Args:
            struct_name: 结构体名称（如 EntrustStatus）
            struct_def: 结构体定义字典，包含name, type, fields

        Returns:
            生成的C++代码字符串
        """
        cpp_struct_name = f"{struct_name}"

        # 获取字段列表
        fields = struct_def.get('fields', [])
        if not fields:
            return ""
        struct_description = struct_def.get('name', '')
        # 开始生成代码
        lines = [
            f"// {struct_description}",
            f"struct {cpp_struct_name} {{",
            "    enum Em {"
        ]

        # 生成每个枚举项
        for field in fields:
            key = field.get('key', '')
            val = field.get('val', '')
            name = field.get('name', '')

            # 所有值都用单引号包围作为字符常量
            val_str = f"'{val}'"

            # 生成枚举项
            lines.append(f"        {key} = {val_str},\t// {name}")

        lines.append("    };")
        lines.append("};\n")

        return '\n'.join(lines)

    def generate_all_structs(self, data: Dict[str, Any]) -> str:
        """生成所有结构体的C++代码"""
        struct_codes = []

        for struct_name, struct_def in data.items():
            code = self.generate_struct_code(struct_name, struct_def)
            if code:
                struct_codes.append(code)

        return '\n'.join(struct_codes)

    def update_header_file(self, generated_code: str):
        """更新头文件中的自动生成代码部分"""
        if not self.header_path.exists():
            raise FileNotFoundError(f"头文件不存在: {self.header_path}")

        # 读取现有文件
        with open(self.header_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # 查找标记位置
        begin_marker = "#define GTRADE_AUTO_CODE_DICT_BEGIN"
        end_marker = "#define GTRADE_AUTO_CODE_DICT_END"

        begin_pos = content.find(begin_marker)
        end_pos = content.find(end_marker)

        if begin_pos == -1 or end_pos == -1:
            raise ValueError(f"在 {self.header_path} 中找不到标记: {begin_marker} 或 {end_marker}")

        # 计算插入位置
        begin_insert = begin_pos + len(begin_marker)

        # 构造新内容
        new_content = (
            content[:begin_insert] + '\n' +
            generated_code + '\n' +
            content[end_pos:]
        )

        # 使用lazy_write_file，只在内容变化时才写入
        lazy_write_file(str(self.header_path), new_content)

        print(f"✓ 成功更新 {self.header_path}")

    def run(self):
        """运行生成器"""
        try:
            print(f"读取 YAML 文件: {self.yaml_path}")
            data = self.load_yaml()

            print(f"生成 C++ 代码...")
            generated_code = self.generate_all_structs(data)

            print(f"更新头文件: {self.header_path}")
            self.update_header_file(generated_code)

            print("\n生成完成！")
            print(f"\n生成的代码:\n{'-' * 60}")
            print(generated_code)
            print('-' * 60)

        except Exception as e:
            print(f"✗ 错误: {e}", file=sys.stderr)
            sys.exit(1)


def main():
    generator = DictGenerator()
    generator.run()


if __name__ == '__main__':
    main()
