#!/usr/bin/env python3
# coding=utf-8
"""
XML to C++ Header Generator
根据 db_tables.xml 中的表定义生成对应的 C++ 头文件

Usage:
    python xml_to_header_generator.py

Author: Auto-generated by Claude Code
Date: 2025-07-13
"""

import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# 导入lazy_write_file工具函数
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from utils.file_utils import lazy_write_file


class XMLToHeaderGenerator:
    """XML表定义到C++头文件的生成器"""
    
    def __init__(self):
        # MySQL类型到C++类型的映射
        self.type_mapping = {
            'int64_t': 'int64_t',
            'int': 'int',
            'double': 'double',
            'float': 'float',
            'char': 'char',  # 需要根据size确定是否为数组
            'bool': 'bool',
            'uint64_t': 'uint64_t',
            'uint32_t': 'uint32_t',
            'uint16_t': 'uint16_t',
            'uint8_t': 'uint8_t',
            'string': 'std::string',
        }
    
    def _convert_type_to_cpp(self, field_type: str, size: Optional[str] = None, cpp_type: Optional[str] = None) -> str:
        """将XML类型转换为C++类型

        支持两种格式：
        1. 新格式：直接使用自定义类型名（如 type="DateTimeCs"）
        2. 旧格式：使用 cpp_type 属性（如 type="char" size="32" cpp_type="DateTimeCs"）
        """
        # 优先使用指定的cpp_type
        if cpp_type:
            return cpp_type

        # 新格式：检查是否是自定义类型（以Cs结尾）
        if field_type.endswith('Cs'):
            return field_type

        # 处理基本类型
        if field_type == 'char' and size:
            if size == '1':
                return 'char'
            else:
                # 根据现有代码，char数组使用Cs后缀的类型定义
                return f'char[{size}]'

        return self.type_mapping.get(field_type, 'std::string')
    
    def _parse_struct_xml(self, struct_element: ET.Element) -> Dict:
        """解析结构体定义

        通过cpp_field属性标识需要在C++头文件中生成的字段
        优先使用st_name作为结构体名称，如果不存在则使用name
        """
        # 优先使用st_name，如果不存在则使用name
        struct_name = struct_element.get('st_name')
        if not struct_name:
            return {}

        struct_info = {
            'name': struct_name,
            'comment': struct_element.get('comment', ''),
            'fields': []
        }

        # 解析字段
        fields_element = struct_element.find('fields')
        if fields_element is not None:
            for field in fields_element.findall('field'):
                # 所有字段都需要同时出现在SQL和.h文件中，不需要过滤
                field_info = {
                    'name': field.get('name'),
                    'type': field.get('type'),
                    'size': field.get('size'),
                    'cpp_type': field.get('cpp_type'),  # 自定义C++类型
                    'not_null': field.get('not_null', 'false').lower() == 'true',
                    'comment': field.get('comment', ''),
                    'default': field.get('default')
                }
                struct_info['fields'].append(field_info)

        return struct_info
    
    def _generate_field_declaration(self, field: Dict) -> Tuple[str, str]:
        """生成单个字段的C++声明，返回(类型声明, 注释)"""
        # 使用新的转换函数，支持cpp_type属性
        cpp_type = self._convert_type_to_cpp(
            field['type'],
            field.get('size'),
            field.get('cpp_type')
        )
        field_name = field['name']
        comment = field['comment']

        # 处理C++数组语法：char name[size] 而不是 char[size] name
        if cpp_type.startswith('char[') and cpp_type.endswith(']'):
            # 提取数组大小部分
            array_part = cpp_type  # 如 "char[kMarketSz]"
            declaration = f"    {array_part.replace('[', f' {field_name}[', 1)};"
        else:
            declaration = f"    {cpp_type} {field_name};"

        return declaration, comment
    
    def _generate_struct_definition(self, struct_info: Dict) -> str:
        """生成结构体定义"""
        lines = []

        # 添加结构体注释
        if struct_info['comment']:
            lines.append(f"// {struct_info['comment']}")

        # 结构体开始
        struct_name = struct_info['name']
        lines.append(f"struct {struct_name} {{")

        # 添加字段（保留注释分组）
        prev_was_comment = False
        for i, field in enumerate(struct_info['fields']):
            declaration, comment = self._generate_field_declaration(field)

            # 检测注释行（在XML中可能作为分组标识）
            # 通过字段间的间隔来判断是否需要添加分组注释
            # 这里简化处理，直接生成字段
            if comment:
                lines.append(f"{declaration}  // {comment}")
            else:
                lines.append(declaration)

        # 结构体结束
        lines.append("};")

        return '\n'.join(lines)
    
    def parse_xml_file(self, xml_path: str) -> List[Dict]:
        """解析db_tables目录，返回所有结构体的定义

        每个<table>或<struct>元素代表一个结构体
        """
        if os.path.isdir(xml_path):
            return self._parse_xml_directory(xml_path)
        else:
            raise FileNotFoundError(f"XML目录不存在: {xml_path}")

    def _parse_xml_directory(self, xml_dir: str) -> List[Dict]:
        """解析db_tables目录下的所有XML文件"""
        structs = []

        # 获取所有XML文件
        xml_files = sorted([f for f in os.listdir(xml_dir) if f.endswith('.xml') and not f.startswith('db_tables_old')])

        # 解析所有表定义作为结构体
        for xml_file in xml_files:
            xml_path = os.path.join(xml_dir, xml_file)
            try:
                tree = ET.parse(xml_path)
                root = tree.getroot()

                if root.tag == 'table':
                    struct_info = self._parse_struct_xml(root)
                    if struct_info:
                        structs.append(struct_info)
                    # print(f"  加载结构体: {struct_info['name']} <- {xml_file}")
            except ET.ParseError as e:
                print(f"  警告: 解析文件 {xml_file} 失败: {e}")

        return structs
    
    def generate_header_file(self, structs: List[Dict], output_dir: str, filename: str = "db_structures.h") -> str:
        """生成C++头文件"""
        lines = []
        
        # 头文件保护和包含
        guard_name = filename.upper().replace('.', '_').replace('-', '_')
        lines.append(f"#pragma once")
        lines.append("")
        lines.append('#include "pch.h"')
        lines.append('#include "str_types.h"')
        lines.append("")
        lines.append("// 自动生成的数据库结构体定义")
        lines.append("// 来源: db_tables.xml")
        lines.append("")
        
        # 生成所有结构体
        for i, struct_info in enumerate(structs):
            if i > 0:
                lines.append("")  # 结构体之间的空行
            
            struct_definition = self._generate_struct_definition(struct_info)
            lines.append(struct_definition)
        
        # 文件结尾
        lines.append("")
        
        full_content = '\n'.join(lines)

        # 使用lazy_write_file，只在内容变化时才写入
        output_path = os.path.join(output_dir, filename)
        os.makedirs(output_dir, exist_ok=True)

        lazy_write_file(output_path, full_content)

        return output_path
    
    def generate_individual_headers(self, structs: List[Dict], output_dir: str) -> List[str]:
        """为每个结构体生成单独的头文件"""
        generated_files = []
        
        for struct_info in structs:
            try:
                filename = f"{struct_info['name']}_struct.h"
                
                lines = []
                
                # 头文件保护和包含
                guard_name = filename.upper().replace('.', '_').replace('-', '_')
                lines.append(f"#pragma once")
                lines.append("")
                lines.append('#include "pch.h"')
                lines.append('#include "str_types.h"')
                lines.append("")
                lines.append(f"// {struct_info['name']} 结构体定义")
                lines.append("// 来源: db_tables.xml")
                lines.append("")
                
                # 生成结构体
                struct_definition = self._generate_struct_definition(struct_info)
                lines.append(struct_definition)
                lines.append("")
                
                full_content = '\n'.join(lines)

                # 使用lazy_write_file，只在内容变化时才写入
                output_path = os.path.join(output_dir, filename)
                os.makedirs(output_dir, exist_ok=True)

                lazy_write_file(output_path, full_content)

                generated_files.append(output_path)
                print(f"✓ 生成头文件: {output_path}")
                
            except Exception as e:
                print(f"✗ 生成结构体 {struct_info['name']} 头文件失败: {e}")
        
        return generated_files

    def generate_all_headers(self, xml_path: str, output_dir: str) -> List[str]:
        """生成所有结构体的合并头文件"""
        structs = self.parse_xml_file(xml_path)
        generated_files = []

        print(f"找到 {len(structs)} 个结构体定义")

        # 生成合并的头文件
        try:
            output_path = self.generate_header_file(structs, output_dir, "db_structures.h")
            generated_files.append(output_path)
            print(f"✓ 生成合并头文件: {output_path}")
        except Exception as e:
            print(f"✗ 生成合并头文件失败: {e}")

        return generated_files


if __name__ == '__main__':
    # 配置参数
    xml_path = '../../common/db_tables'
    output_dir = '../../interface'

    # 转换为绝对路径
    xml_path = os.path.abspath(xml_path)
    output_dir = os.path.abspath(output_dir)

    print(f"XML文件路径: {xml_path}")
    print(f"输出目录: {output_dir}")

    generator = XMLToHeaderGenerator()
    generated_files = generator.generate_all_headers(xml_path, output_dir)

    print(f"\n成功生成 {len(generated_files)} 个头文件:")
    for file_path in generated_files:
        print(f"  - {file_path}")

    print(f"\n所有文件已生成到: {output_dir}")
        
