#!/usr/bin/env python3
# coding=utf-8
"""
XML to SQL Generator
根据 db_tables.xml 中的表定义生成对应的 SQL 文件

Usage:
    python xml_to_sql_generator.py

Author: Auto-generated by Claude Code
Date: 2025-07-12
"""

import os
import sys
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# 导入lazy_write_file工具函数
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from utils.file_utils import lazy_write_file


SPECIAL_TYPE_LEN = {
    'CharCs': 1,
}


class XMLToSQLGenerator:
    """XML表定义到SQL文件的生成器"""
    
    def __init__(self, str_types_path: Optional[str] = None):
        # C++类型到MySQL类型的映射
        self.type_mapping = {
            'int64_t': 'BIGINT',
            'int': 'INT',
            'double': 'DOUBLE',
            'float': 'FLOAT',
            'char': 'VARCHAR',  # 需要根据size确定长度
            'bool': 'TINYINT(1)',
            'uint64_t': 'BIGINT UNSIGNED',
            'uint32_t': 'INT UNSIGNED',
            'uint16_t': 'SMALLINT UNSIGNED',
            'uint8_t': 'TINYINT UNSIGNED',
            'string': 'TEXT',
            'timestamp': 'TIMESTAMP',
        }

        # 从str_types.h中解析自定义类型和大小的映射
        # 例如: {'DateTimeCs': 32, 'MarketCs': 16, ...}
        self.custom_type_sizes = {}
        if str_types_path:
            self._parse_str_types_h(str_types_path)
        else:
            # 默认路径
            default_path = os.path.join(os.path.dirname(__file__), '../../interface/str_types.h')
            if os.path.exists(default_path):
                self._parse_str_types_h(default_path)

    def _parse_str_types_h(self, file_path: str) -> None:
        """解析str_types.h文件，提取自定义类型定义

        解析格式：DECLARE_STR_TYPE(DateTime, 32);
        生成映射：{'DateTimeCs': 32, 'DateTimeAs': 32}
        """
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # 匹配 DECLARE_STR_TYPE(TypeName, size) 的模式
            # 例如: DECLARE_STR_TYPE(DateTime, 32);
            pattern = r'DECLARE_STR_TYPE\s*\(\s*(\w+)\s*,\s*(\d+)\s*\)'
            matches = re.findall(pattern, content)

            for type_name, size in matches:
                # DECLARE_STR_TYPE(DateTime, 32) 定义了：
                # - DateTimeCs: char[32] 类型
                # - DateTimeAs: std::array<char, 32> 类型
                cs_type = f"{type_name}Cs"
                if cs_type in SPECIAL_TYPE_LEN:
                    self.custom_type_sizes[cs_type] = SPECIAL_TYPE_LEN[cs_type]
                else:
                    self.custom_type_sizes[cs_type] = int(size)

            if self.custom_type_sizes:
                print(f"从 {file_path} 加载了 {len(self.custom_type_sizes)} 个自定义类型定义")
        except Exception as e:
            print(f"警告: 解析 str_types.h 失败: {e}")

    def _convert_cpp_type_to_mysql(self, field_type: str, size: Optional[str] = None) -> str:
        """将C++类型转换为MySQL类型

        支持两种格式：
        1. 新格式：自定义类型（如 type="DateTimeCs"），从str_types.h查找大小
        2. 旧格式：基本类型+size（如 type="char" size="32"）
        """
        # 新格式：检查是否是自定义类型（以Cs结尾）
        if field_type.endswith('Cs'):
            if field_type in self.custom_type_sizes:
                type_size = self.custom_type_sizes[field_type]
                if type_size == 1:
                    return 'CHAR(1)'
                else:
                    return f'VARCHAR({type_size})'
            else:
                print(f"警告: 未找到自定义类型 {field_type} 的大小定义，使用默认 TEXT 类型")
                return 'TEXT'

        # 旧格式：处理基本类型
        if field_type == 'char' and size:
            if size == '1':
                return 'CHAR(1)'
            else:
                return f'VARCHAR({size})'

        return self.type_mapping.get(field_type, 'TEXT')
    
    def _parse_struct_xml(self, struct_element: ET.Element) -> Dict:
        """解析结构体定义"""
        struct_info = {
            'name': struct_element.get('name'),
            'comment': struct_element.get('comment', ''),
            'fields': []
        }

        # 解析字段
        fields_element = struct_element.find('fields')
        if fields_element is not None:
            for field in fields_element.findall('field'):
                field_info = {
                    'name': field.get('name'),
                    'type': field.get('type'),
                    'size': field.get('size'),
                    'not_null': field.get('not_null', 'false').lower() == 'true',
                    'comment': field.get('comment', ''),
                    'default': field.get('default'),
                    'auto_increment': field.get('auto_increment', 'false').lower() == 'true'
                }
                struct_info['fields'].append(field_info)

        return struct_info
    
    def _parse_table_xml(self, table_element: ET.Element, structs_dict: Dict) -> List[Dict]:
        """解析单个表的XML定义，支持多个 indexes 元素

        新格式：<indexes table_name="..."> 包含 <primary_key> 和 <index> 元素
        旧格式兼容：<table name="done" struct="Done"> 引用结构体定义

        返回值：表定义列表（如果有多个 indexes，则返回多个表定义）
        """
        table_name = table_element.get('name')
        struct_name = table_element.get('st_name', '')

        # 解析字段（所有表共享）
        shared_fields = []
        fields_element = table_element.find('fields')
        if fields_element is not None:
            for field in fields_element.findall('field'):
                field_info = {
                    'name': field.get('name'),
                    'type': field.get('type'),
                    'size': field.get('size'),
                    'not_null': field.get('not_null', 'false').lower() == 'true',
                    'comment': field.get('comment', ''),
                    'default': field.get('default'),
                    'auto_increment': field.get('auto_increment', 'false').lower() == 'true'
                }
                shared_fields.append(field_info)
        # 旧格式：从结构体定义中获取字段信息
        elif struct_name in structs_dict:
            shared_fields = structs_dict[struct_name]['fields'].copy()

        # 解析表选项（所有表共享）
        shared_options = {}
        options_element = table_element.find('options')
        if options_element is not None:
            for option in options_element.findall('option'):
                shared_options[option.get('name')] = option.text

        # 解析所有 indexes 元素（支持多个，每个 indexes 对应一个表）
        # 新格式：<indexes table_name="..."> 包含 <primary_key> 和 <index>
        # 旧格式：<indexes> 只包含 <index>（不带 table_name 属性）
        all_indexes_elements = table_element.findall('indexes')
        indexes_elements = [idx for idx in all_indexes_elements if idx.get('table_name')]

        # 如果没有新格式的 indexes 元素，尝试旧格式的 primary_key
        if not indexes_elements:
            # 兼容旧格式：单个 primary_key 元素 + 旧格式 indexes 元素
            primary_key_element = table_element.find('primary_key')

            # 解析旧格式的 indexes（不带 table_name 属性）
            old_indexes = []
            old_indexes_element = table_element.find('indexes')
            if old_indexes_element is not None and not old_indexes_element.get('table_name'):
                for index in old_indexes_element.findall('index'):
                    index_info = {
                        'name': index.get('name'),
                        'type': index.get('type', 'index'),
                        'fields': []
                    }
                    for field in index.findall('field'):
                        index_info['fields'].append(field.text)
                    old_indexes.append(index_info)

            sql_table_name = self._convert_struct_name_to_table_name(table_name)
            table_info = {
                'name': sql_table_name,
                'struct': struct_name,
                'comment': table_element.get('comment', ''),
                'fields': shared_fields.copy(),
                'primary_key': [],
                'indexes': old_indexes,
                'options': shared_options.copy()
            }

            # 解析主键字段
            if primary_key_element is not None:
                for field in primary_key_element.findall('field'):
                    table_info['primary_key'].append(field.text)

            return [table_info]

        # 为每个 indexes 元素创建一个表定义
        table_infos = []
        for indexes_element in indexes_elements:
            # 从 indexes 的 table_name 属性获取表名
            idx_table_name = indexes_element.get('table_name')
            if not idx_table_name:
                # 如果没有 table_name 属性，使用默认表名
                idx_table_name = self._convert_struct_name_to_table_name(table_name)

            # 优先使用 indexes 的 comment 属性，如果没有则使用 table 的 comment
            idx_comment = indexes_element.get('comment')
            if not idx_comment:
                idx_comment = table_element.get('comment', '')

            table_info = {
                'name': idx_table_name,  # SQL表名（从 indexes 的 table_name 属性获取）
                'struct': struct_name,   # C++结构体名（首字母大写）
                'comment': idx_comment,  # 优先使用 indexes 的 comment
                'fields': shared_fields.copy(),
                'primary_key': [],
                'indexes': [],
                'options': shared_options.copy()
            }

            # 解析 primary_key 元素
            primary_key_element = indexes_element.find('primary_key')
            if primary_key_element is not None:
                for field in primary_key_element.findall('field'):
                    table_info['primary_key'].append(field.text)

            # 解析 index 元素列表
            for index in indexes_element.findall('index'):
                index_info = {
                    'name': index.get('name'),
                    'type': index.get('type', 'index'),
                    'fields': []
                }
                for field in index.findall('field'):
                    index_info['fields'].append(field.text)
                table_info['indexes'].append(index_info)

            table_infos.append(table_info)

        return table_infos

    def _convert_struct_name_to_table_name(self, struct_name: str) -> str:
        """将结构体名转换为表名

        Done -> done
        Entrust -> entrust
        KLine_1M -> kline_1m
        """
        # 简单地转换为小写，保持原有的下划线
        # 如果原名中已有下划线（如KLine_1M），只需转小写即可
        return struct_name.lower()
    
    def _generate_field_sql(self, field: Dict) -> str:
        """生成单个字段的SQL定义"""
        mysql_type = self._convert_cpp_type_to_mysql(field['type'], field['size'])

        sql_parts = [f"`{field['name']}`", mysql_type]

        # 添加NOT NULL约束
        if field['not_null']:
            sql_parts.append('NOT NULL')

        # 添加AUTO_INCREMENT
        if field.get('auto_increment'):
            sql_parts.append('AUTO_INCREMENT')

        # 添加默认值
        if field.get('default'):
            sql_parts.append(f"DEFAULT {field['default']}")

        # 添加注释
        if field['comment']:
            sql_parts.append(f"COMMENT '{field['comment']}'")

        return ' '.join(sql_parts)
    
    def _generate_create_table_sql(self, table_info: Dict) -> str:
        """生成CREATE TABLE语句"""
        lines = []

        # 表注释
        lines.append(f"-- {table_info['comment']}")
        if table_info['struct']:
            lines.append(f"-- 对应C++结构体: {table_info['struct']}")
        lines.append("")

        # CREATE TABLE开始
        lines.append(f"-- {table_info['comment']}")
        lines.append(f"CREATE TABLE IF NOT EXISTS `{table_info['name']}` (")

        # 字段定义
        field_lines = []
        for field in table_info['fields']:
            field_lines.append(f"    {self._generate_field_sql(field)}")

        # 主键定义
        if table_info['primary_key']:
            pk_fields = ', '.join([f"`{field}`" for field in table_info['primary_key']])
            field_lines.append(f"    PRIMARY KEY ({pk_fields})")

        # 索引定义
        for index in table_info['indexes']:
            index_fields = ', '.join([f"`{field}`" for field in index['fields']])
            if index['type'] == 'unique':
                field_lines.append(f"    UNIQUE KEY `{index['name']}` ({index_fields})")
            else:
                field_lines.append(f"    KEY `{index['name']}` ({index_fields})")

        lines.append(',\n'.join(field_lines))

        # 表选项
        option_parts = []

        # 从options中获取engine和charset
        if table_info.get('options'):
            engine = table_info['options'].get('engine', 'InnoDB')
            charset = table_info['options'].get('charset', 'utf8mb4')
        else:
            engine = 'InnoDB'
            charset = 'utf8mb4'

        option_parts.append(f") ENGINE={engine} DEFAULT CHARSET={charset}")

        # 添加COMMENT
        if table_info['comment']:
            option_parts.append(f"COMMENT='{table_info['comment']}'")

        lines.append(' '.join(option_parts) + ";")

        return '\n'.join(lines)
    
    def parse_xml_file(self, xml_path: str) -> List[Dict]:
        """解析XML文件，返回所有表的定义

        兼容两种格式:
        1. 旧格式: 单个db_tables.xml文件包含所有结构体和表定义
        2. 新格式: db_tables目录下的多个XML文件，每个文件一个struct或table
        """
        if os.path.isfile(xml_path):
            # 旧格式: 单个文件
            return self._parse_single_xml_file(xml_path)
        elif os.path.isdir(xml_path):
            # 新格式: 目录
            return self._parse_xml_directory(xml_path)
        else:
            raise FileNotFoundError(f"XML文件或目录不存在: {xml_path}")

    def _parse_single_xml_file(self, xml_path: str) -> List[Dict]:
        """解析单个XML文件（旧格式）"""
        try:
            tree = ET.parse(xml_path)
            root = tree.getroot()
        except ET.ParseError as e:
            raise ValueError(f"XML文件解析错误: {e}")

        # 解析结构体定义
        structs_dict = {}
        structs_element = root.find('structs')
        if structs_element is not None:
            for struct_element in structs_element.findall('struct'):
                struct_info = self._parse_struct_xml(struct_element)
                structs_dict[struct_info['name']] = struct_info

        # 解析表定义
        tables = []
        tables_element = root.find('tables')
        if tables_element is not None:
            for table_element in tables_element.findall('table'):
                # _parse_table_xml 现在返回一个列表（支持多个primary_key）
                table_infos = self._parse_table_xml(table_element, structs_dict)
                for table_info in table_infos:
                    tables.append(table_info)

        return tables

    def _parse_xml_directory(self, xml_dir: str) -> List[Dict]:
        """解析db_tables目录下的所有XML文件（新格式）

        新格式：每个XML文件是一个<table>元素，包含所有定义
        旧格式兼容：<struct>元素单独定义，<table>元素引用struct
        支持多个primary_key：一个XML文件可以生成多个SQL表
        """
        structs_dict = {}
        tables = []

        # 获取所有XML文件
        xml_files = sorted([f for f in os.listdir(xml_dir) if f.endswith('.xml') and not f.startswith('db_tables_old')])

        # 第一遍: 解析所有结构体（兼容旧格式）
        for xml_file in xml_files:
            xml_path = os.path.join(xml_dir, xml_file)
            try:
                tree = ET.parse(xml_path)
                root = tree.getroot()

                if root.tag == 'struct':
                    struct_info = self._parse_struct_xml(root)
                    structs_dict[struct_info['name']] = struct_info
                    print(f"  加载结构体: {struct_info['name']} <- {xml_file}")
            except ET.ParseError as e:
                print(f"  警告: 解析文件 {xml_file} 失败: {e}")

        # 第二遍: 解析所有表定义（新格式）
        for xml_file in xml_files:
            xml_path = os.path.join(xml_dir, xml_file)
            try:
                tree = ET.parse(xml_path)
                root = tree.getroot()

                if root.tag == 'table':
                    # _parse_table_xml 现在返回一个列表（支持多个primary_key）
                    table_infos = self._parse_table_xml(root, structs_dict)
                    for table_info in table_infos:
                        tables.append(table_info)
                        print(f"  加载表: {table_info['name']} (struct: {table_info['struct']}) <- {xml_file}")
            except ET.ParseError as e:
                print(f"  警告: 解析文件 {xml_file} 失败: {e}")

        return tables
    
    def generate_sql_file(self, table_info: Dict, output_dir: str) -> str:
        """为单个表生成SQL文件"""
        sql_content = self._generate_create_table_sql(table_info)

        # 构建完整内容（不需要额外的header，因为已经在_generate_create_table_sql中生成了）
        full_content = sql_content + '\n'

        # 使用lazy_write_file，只在内容变化时才写入
        output_path = os.path.join(output_dir, f"{table_info['name']}.sql")
        os.makedirs(output_dir, exist_ok=True)

        lazy_write_file(output_path, full_content)

        return output_path

    def generate_all_tables(self, xml_path: str, output_dir: str) -> List[str]:
        """生成所有表的SQL文件"""
        tables = self.parse_xml_file(xml_path)
        generated_files = []
        
        print(f"找到 {len(tables)} 个表定义")
        
        for table_info in tables:
            try:
                output_path = self.generate_sql_file(table_info, output_dir)
                generated_files.append(output_path)
                print(f"✓ 生成SQL文件: {output_path}")
            except Exception as e:
                print(f"✗ 生成表 {table_info['name']} 失败: {e}")
        
        return generated_files


if __name__ == '__main__':
    # 配置参数
    # 使用db_tables目录（新格式）
    xml_path = '../../common/db_tables'
    output_dir = '../../../deploy/sql'

    # 转换为绝对路径
    xml_path = os.path.abspath(xml_path)
    output_dir = os.path.abspath(output_dir)

    print(f"XML文件路径: {xml_path}")
    print(f"输出目录: {output_dir}")

    generator = XMLToSQLGenerator()
    generated_files = generator.generate_all_tables(xml_path, output_dir)

    print(f"\n成功生成 {len(generated_files)} 个SQL文件:")
    for file_path in generated_files:
        print(f"  - {file_path}")

    print(f"\n所有文件已生成到: {output_dir}")



