-- 委托表
-- 对应C++结构体: Order

-- 委托表
CREATE TABLE IF NOT EXISTS `order` (
    `entno` BIGINT COMMENT '委托号',
    `status` CHAR(1) COMMENT '委托状态',
    `fmt_time` BIGINT COMMENT '格式化时间',
    `market` VARCHAR(16) COMMENT '市场',
    `account_id` VARCHAR(32) COMMENT '账户ID',
    `portfolio` VARCHAR(32) COMMENT '组合',
    `inst_type` CHAR(1) COMMENT '标的类型',
    `inst_id` VARCHAR(32) COMMENT '标的名称',
    `inst_id_code` BIGINT COMMENT '标的唯一标识代码',
    `policy_no` VARCHAR(32) COMMENT '策略编号',
    `private_no` VARCHAR(64) COMMENT '私有号',
    `bs_side` CHAR(1) COMMENT '买卖方向(B/S)',
    `pos_side` CHAR(1) COMMENT '持仓方向',
    `oc_side` CHAR(1) COMMENT '开平方向',
    `trade_mode` CHAR(1) COMMENT '交易模式',
    `price_type` CHAR(1) COMMENT '价格类型',
    `price` DOUBLE COMMENT '价格',
    `amount` DOUBLE COMMENT '数量',
    `ent_time` BIGINT COMMENT '委托时间(纳秒)',
    `expire_time` BIGINT COMMENT '委托超时时间(纳秒)',
    `ex_entno` BIGINT COMMENT '交易所委托号',
    `filled_px` DOUBLE COMMENT '成交均价',
    `filled` DOUBLE COMMENT '成交数量',
    `remain` DOUBLE COMMENT '剩余数量',
    `confirm_time` BIGINT COMMENT '委托确认时间(纳秒)',
    `filled_time` BIGINT COMMENT '成交时间(纳秒)',
    `update_time` BIGINT COMMENT '更新时间(纳秒)',
    `source` CHAR(1) COMMENT '委托来源',
    `err_code` INT COMMENT '错误码',
    `err_msg` VARCHAR(128) COMMENT '错误消息',
    `drawno` BIGINT COMMENT '撤单号',
    `draw_amt` DOUBLE COMMENT '撤单数量',
    `withdraw_time` BIGINT COMMENT '撤单时间(纳秒)',
    `status_id` INT COMMENT '订单状态id',
    `status_gid` BIGINT COMMENT '订单状态全局id',
    `trd_px` DOUBLE COMMENT '最近一笔成交价',
    `trd_qty` DOUBLE COMMENT '最近一笔成交量',
    PRIMARY KEY (`entno`),
    KEY `idx_policy_no` (`policy_no`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='委托表';
